services:
  localstack:
    image: localstack/localstack:3.0
    ports:
      - "4566:4566"
    environment:
      - DEFAULT_REGION=us-east-1
      - SERVICES=dynamodb,sqs
      - DEBUG=0

  jaeger:
    image: jaegertracing/all-in-one:1.50
    ports:
      - "16686:16686"
      - "4318:4318"
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
