spring:
  application:
    name: ticketorchestra
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      endpoint: http://localhost:4566
      dynamodb:
        endpoint: http://localhost:4566
      sqs:
        endpoint: http://localhost:4566

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ticketorchestra
      environment: local
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
